[nixpacks]
phases.build.setup = [
  apt-get update,
  apt-get install -y wget gnupg ca-certificates,
  apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1 libgobject-2.0-0
]

[phases.setup]
nixPkgs = [nodejs_18, npm]

[start]
cmd = npm run start
